<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title><?php echo $title?></title>
    <meta name="keywords" content="<?php echo $keywords?>" />
    <meta name="description" content="<?php echo $description?>" />
  </head>
  <body>
    <?php echo lang('{%user_center%}')?>
  </body>
</html>
