<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title><?php echo $title?></title>
    <meta name="keywords" content="<?php echo $keywords?>" />
    <meta name="description" content="<?php echo $description?>" />
    <link href="/static/index/css/register.css" rel="stylesheet" />
  </head>
  <script>
    function showText(elm, text) {
      elm.type = text ? 'text': 'password';
      elm.focus();
    }
    /*window.onload = function() {
      if (-1 == navigator.appVersion.indexOf('MSIE 8.0')) {
        document.getElementById('show-password').style.display = 'inline'; 
      }
    }*/
  </script>
  <body>
    <!--
    <form action="/user/register" method="post">
    <h2><?php //echo $title?></h2>
    用户名<br> <input type="text" name="user_name" placeholder="用户名"><br><br>
    邮箱<br> <input type="text" name="email" placeholder="邮箱"><br><br>
    密码<br> <input type="password" name="password" placeholder="密码"> <label id="show-password" style="cursor:pointer;display:none"><input type="checkbox" onclick="showText(document.getElementsByName('password')[0], this.checked)">显示密码</label><br><br>
    <input type="hidden" name="signature" value="<?php //echo $signature?>">
    <input type="submit" value="注册"> <a href="/user/login">已有帐号</a>
    </form>-->
    <form action="/user/register" method="post">
    	<ul class="ul-register">
        	<li><label><?php echo lang('{%username%}')?></label><input class="input-text" name="user_name" type="text" /></li>
            <li><label><?php echo lang('{%email%}')?></label><input class="input-text" name="email" type="text" /></li>
            <li><label><?php echo lang('{%password%}')?></label><input class="input-text" name="password" type="password" /></li>
            <li><label><?php echo lang('{%confirm_pwd%}')?></label><input class="input-text" name="" type="text" /></li>
            <input type="hidden" name="signature" value="<?php $signature?>">
            <li class="termswrap">
                <input name="" type="checkbox" value="" /><span class="terms">
                <?php echo lang('{%hvae_read_accept%}')?> <a href="#" class="highlight">
                <?php echo lang('{%copyright_statement%}')?></a> <?php echo lang('{%and%}')?> <a href="#" class="highlight"><?php echo lang('{%privacy_Protect%}')?></a> <?php echo lang('{%clause%}')?> </span>
            </li>
            <li class="btn-register">
                <button class="btn-serch subset"><?php echo lang('{%register_now%}')?></button>
                <input type="hidden" name="signature" value="<?php echo $signature?>" />
                <!--<span>　<?php /*echo lang('{%have_register_pls%}')*/?> <a href="/user/login" class="highlight"><?php /*echo lang('{%login%}')*/?></a></span>-->
            </li>
        </ul>
    </form>
    
  </body>
</html>
