<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title><?php echo $title?></title>
    <meta name="keywords" content="<?php echo $keywords?>" />
    <meta name="description" content="<?php echo $description?>" />
  </head>
  <body>
    <form action="/user/resetpassword_step1" method="post">
    <h2><?php echo $title?></h2>
    <?php echo lang('{%account%}')?><br> <input type="text" name="account" placeholder="<?php echo lang('{%username_or_email%}')?>"><br><br>
    <input type="hidden" name="signature" value="<?php echo $signature?>">
    <input type="submit" value="<?php echo lang('{%reset_pwd_link%}')?>"> <a href="/user/login"><?php echo lang('{%login%}')?></a> <a href="/user/register"><?php echo lang('{%no_account%}')?></a>
    </form>
  </body>
</html>
