<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title><?php echo $title?></title>
    <meta name="keywords" content="<?php echo $keywords?>" />
    <meta name="description" content="<?php echo $description?>" />
  </head>
  <script>
    function showText(elm, text) {
      elm.type = text ? 'text': 'password';
      elm.focus();
    }
    window.onload = function() {
      if (-1 == navigator.appVersion.indexOf('MSIE 8.0')) {
        document.getElementById('show-password').style.display = 'inline'; 
      }
    }
  </script>
  <body>
    <form action="/user/savePassword" method="post">
    <h2><?php echo $title?></h2>
    <?php echo lang('{%account%}')?><br> <input type="text" name="account" readonly placeholder="<?php echo $email?>"><br><br>
    <?php echo lang('{%password%}')?><br> <input type="password" name="password" placeholder="<?php echo lang('{%password%}')?>"> <label id="show-password" style="cursor:pointer;display:none"><input type="checkbox" onclick="showText(document.getElementsByName('password')[0], this.checked)"><?php echo lang('{%display_pwd%}')?></label><br><br>
    <input type="hidden" name="code" value="<?php echo $code?>">
    <input type="submit" value="<?php echo lang('{%save_pwd%}')?>">
    </form>
  </body>
</html>
